### ISSUE TITLE
wezterm flatpak crashes on Fedora 38

### ISSUE THREAD

**Issue by akdev1l** [flathub/org.wezfurlong.wezterm#12] opened 2023-05-07 17:21 UTC
the application crashes:

```
$ flatpak run org.wezfurlong.wezterm          
[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
13:19:40.531  ERROR  wezterm_gui > running message loop: error during event_q.read_events protocol_error=Some(ProtocolError { code: 7, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating
```

some system information:

```
$ uname -a
Linux toronto.hq.akdev.xyz 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64 GNU/Linux
[akdev@toronto ~ ]$ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
```

calling `start` outputs the same:

```
$ flatpak run org.wezfurlong.wezterm start 
[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345
13:21:11.994  ERROR  wezterm_gui > running message loop: error during event_q.read_events protocol_error=Some(ProtocolError { code: 7, object_id: 0, object_interface: "<unknown>", message: "" }): Protocol error (os error 71); terminating
```

it'd be great if this would work as I am on fedora silverblue and a flatpak-based terminal fits the containerized workflow

**Comment by wez** [comment] 2023-05-07 17:45
Probably a duplicate of https://github.com/wez/wezterm/issues/3244

**Comment by akdev1l** [comment] 2023-05-07 19:20
yeah that checks out, disabling wayland access via flatseal makes it not crash

sadly, it is very choppy via xwayland

thanks for the quick response

**Comment by wez** [comment] 2023-05-07 21:48
Thanks for confirming! closing this in favor of that issue!

**Closed as completed by wez** 2023-05-07 21:48 UTC
