### ISSUE TITLE
wl_surface@71: error 2: Buffer size (12x1081) must be an integer multiple of the buffer_scale (2).

### ISSUE THREAD

**Issue by almereyda** [flathub/org.wezfurlong.wezterm#15] opened 2023-11-15 23:14 UTC
The `.desktop` file that comes with this package comes with an execution command, which crashes `wezterm` in `wl_surface`.

```shell
$ rg --pcre2 '(?<=^Exec=).*$' -o /var/lib/flatpak/exports/share/applications/org.wezfurlong.wezterm.desktop
7:/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=wezterm org.wezfurlong.wezterm start --cwd .
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=wezterm org.wezfurlong.wezterm start --cwd .
wl_surface@71: error 2: Buffer size (12x1081) must be an integer multiple of the buffer_scale (2).
23:48:16.361  ERROR  wezterm_gui > running message loop: error during event_q.dispatch protocol_error=Some(ProtocolError { code: 2, object_id: 71, object_interface: "wl_surface", message: "" }): Protocol error (os error 71); terminating
```

Running the flatpak without any specified, and supposedly default parameters, does not invoke the crash:

```shell
$ flatpak run wezterm
```

After doing that a few times, running the earlier command also worked again, up until a point.

It then, for example, crashes when resizing with Super + LRUD

![grafik](https://github.com/flathub/org.wezfurlong.wezterm/assets/1645308/eb4629f7-3b91-46f5-a3f2-a172cbe9dca3)

And then it doesn't do it again, for some time.

This happens when executed from `kitty` in `zsh` on GNOME 44 in Fedora 38 with onboard Intel graphics.

These seem related:

- https://github.com/flathub/org.wezfurlong.wezterm/issues/12
- https://github.com/wez/wezterm/issues/3244

**Comment by wez** [comment] 2023-11-16 18:35
I don't own this repo (the flathub org does, and I only have limited permissions here, sufficient to publish to flathub).
I prefer to track issues in the main wezterm repo.
This particular issue sounds like a duplicate of other wayland related issues.
If you feel that this is a different, new issue, then please open a new issue in the wezterm repo.
I'm going to close this one as I can't effectively track and triage issues from this particular flathub repo.

**Closed as completed by wez** 2023-11-16 18:35 UTC

**Comment by almereyda** [comment] 2023-11-18 22:33
Thanks for the explanation. I thought there would be a different maintainer from the community, who could pick up from here.
I will file this again upstream, if it occurs again.
